name: Render PlantUML
on:
  push:
    paths:
      - 'diagrams/**/*.puml'
      - '.github/workflows/render-plantuml.yml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
